-- Execute este script no SQL Editor do seu projeto Supabase (https://app.supabase.com)
-- Tabela baseada no layout da planilha "linha_do_tempo_comite.xlsx" (uma linha por evento,
-- com Hora Inicial / Hora Final em vez de um campo de horas já calculado).

create table if not exists public.linha_do_tempo (
  id bigint generated by default as identity primary key,
  regional text,
  unidade text,
  frente text,                 -- "Descrição do Grupo de Equipamento"
  codigo_equipamento text,
  equipamento text,            -- "Descrição do Equipamento"
  codigo_operador text,
  operador text,               -- "Nome"
  data date not null,
  hora_inicial time not null,
  hora_final time not null,
  codigo_operacao text,
  atividade text not null,     -- "Descrição da Operação"
  classificacao text not null, -- "Descrição do Grupo da Operação" (Produtiva / Improdutivo / Manutenção / ...)
  codigo_fazenda text,
  codigo_zona text,
  codigo_talhao text,
  fazenda text,
  horimetro_inicial numeric,
  horimetro_final numeric,
  horimetro_secundario numeric,
  velocidade_media numeric,
  created_at timestamptz not null default now()
);

create index if not exists linha_do_tempo_data_idx on public.linha_do_tempo (data);
create index if not exists linha_do_tempo_frente_idx on public.linha_do_tempo (frente);
create index if not exists linha_do_tempo_equipamento_idx on public.linha_do_tempo (equipamento);

alter table public.linha_do_tempo enable row level security;

drop policy if exists "Leitura publica" on public.linha_do_tempo;
create policy "Leitura publica" on public.linha_do_tempo
  for select
  using (true);

-- Depois de rodar este script, vá em Database > Replication e habilite a tabela
-- "linha_do_tempo" para o painel receber atualizações automáticas em tempo real.
