-- Execute este script no SQL Editor do seu projeto Supabase (https://app.supabase.com)
-- Ele cria a tabela que alimenta o Painel Comparativo de Eficiência Operacional.

create table if not exists public.apontamentos (
  id bigint generated by default as identity primary key,
  data date not null,
  frente text,
  equipamento text,
  modelo text,
  classificacao_ativ text not null,
  cd_atividade text,
  atividade text not null,
  tempo_decimal numeric not null,
  created_at timestamptz not null default now()
);

create index if not exists apontamentos_data_idx on public.apontamentos (data);
create index if not exists apontamentos_frente_idx on public.apontamentos (frente);
create index if not exists apontamentos_equipamento_idx on public.apontamentos (equipamento);

-- RLS: o painel (HTML público) só precisa de permissão de LEITURA.
-- Inserções/edições você faz logado no Table Editor do Supabase, que já tem acesso total.
alter table public.apontamentos enable row level security;

drop policy if exists "Leitura publica" on public.apontamentos;
create policy "Leitura publica" on public.apontamentos
  for select
  using (true);

-- Importante: depois de rodar este script, vá em Database > Replication
-- e habilite a tabela "apontamentos" para que o painel receba atualizações
-- automáticas em tempo real quando você inserir novas linhas.
